Remove pipeline files

diff --git a/packaging/common/postinst b/packaging/common/postinst
--- a/packaging/common/postinst
+++ b/packaging/common/postinst
@@ -25,7 +25,7 @@ case $1 in
   # Configure OpenSSL to use the engine
   if [ -x /usr/lib/keysinuse/keysinuseutil ]; then
     echo "Enabling keysinuse engine for OpenSSL"
-    /usr/lib/keysinuse/keysinuseutil -update-default install|| echo "Configuring engine failed"
+    /usr/lib/keysinuse/keysinuseutil -update-default install || echo "Configuring engine failed"
   fi
 esac
 
