Add option to symlink library

diff --git a/packaging/common/postinst b/packaging/common/postinst
--- a/packaging/common/postinst
+++ b/packaging/common/postinst
@@ -22,7 +22,7 @@ case $1 in
   # Configure OpenSSL to use the engine
   if [ -x /usr/bin/keysinuseutil ]; then
     echo "Enabling keysinuse engine for OpenSSL"
-    /usr/bin/keysinuseutil -update-default install || echo "Configuring engine failed"
+    /usr/bin/keysinuseutil -update-default -install-library install || echo "Configuring engine failed"
   fi
 esac
 
diff --git a/packaging/common/preinst b/packaging/common/preinst
--- a/packaging/common/preinst
+++ b/packaging/common/preinst
@@ -5,7 +5,7 @@ case $1 in
   # Check if the engine is already configured. Deconfigure first if so
   if [ -x /usr/bin/keysinuseutil ]; then
     echo "Disabling version $2 of keysinuse engine for OpenSSL"
-    /usr/bin/keysinuseutil -update-default uninstall || echo "Failed to deconfigure old version"
+    /usr/bin/keysinuseutil -update-default -install-library uninstall || echo "Failed to deconfigure old version"
   fi
 esac
 
diff --git a/packaging/common/prerm b/packaging/common/prerm
--- a/packaging/common/prerm
+++ b/packaging/common/prerm
@@ -5,7 +5,7 @@ case $1 in
   # Deconfigure engine
   if [ -x /usr/bin/keysinuseutil ]; then
     echo "Disabling keysinuse engine for OpenSSL"
-    /usr/bin/keysinuseutil -update-default uninstall || echo "Deconfiguring keysinuse engine failed"
+    /usr/bin/keysinuseutil -update-default -install-library uninstall || echo "Deconfiguring keysinuse engine failed"
   fi
 
   # Clean up symlink to engine in engines directory
